### ISSUE TITLE
Just wanted to say thank you for the fork!

### ISSUE THREAD

**Issue by GitMurf** [lyz-code/telescope-orgmode.nvim#10]
I know this is not appropriate for a gh issue but I just wanted to say THANK YOU! for making this fork and maintaining it! I was growing so frustrated trying to get the original repo to work.

**Comment by lyz-code** [comment]
Thank you so much for your kind words <3 , I know almost nothing about lua, so far it's been a enlightening but painful project to carry on, I'd definitely could use some help with it if you know anyone that might be interested.

I hope the new version works well with the latest breaking change of orgmode `(•‿•)`

**Comment by GitMurf** [comment]
@lyz-code if you have anything you want me to take a look at I would be happy to. I am pretty new to Lua as well but I am a JavaScript / typescript developer and I have come to find out that lua has a lot of similarities so it hasn't been too hard for me to pickup. Let me know!

**Comment by lyz-code** [comment]
Awesome! the first thing that I'd ask is if you could proactively fix any issue that you find while using the plugin. So far we don't have many issue and PR traffic but if you could subscribe to the repository notifications and help me with it that would be marvelous. 

Finally if you have some spare time, I feel we could really [use some tests](https://github.com/lyz-code/telescope-orgmode.nvim/issues/8) to help in the maintenance of the codebase. Now I feel anxious each time I change a line both because I don't fully understand the whole code and that I don't know what I'm going to break.

**Comment by GitMurf** [comment]
> Awesome @GitMurf ! the first thing that I'd ask is if you could proactively fix any issue that you find while using the plugin. So far we don't have many issue and PR traffic but if you could subscribe to the repository notifications and help me with it that would be marvelous. 

✅ Done... subscribed. 

> Finally if you have some spare time, I feel we could really [use some tests](https://github.com/lyz-code/telescope-orgmode.nvim/issues/8) to help in the maintenance of the codebase...

This one unfortunately is probably my weakest point of knowledge with lua and neovim plugins 😪 this would be a bit more of the blind leading the blind ;)
